[target.x86_64-pc-windows-msvc]
# Using default MSVC linker on Windows - will be set by vcvars64.bat

[target.aarch64-pc-windows-msvc]
# Using default MSVC linker on Windows - will be set by vcvars64.bat

# Note: Cross-compilation requires proper toolchains to be installed
# For now, we'll build for the current platform and copy binaries
# Real cross-compilation can be enabled by installing:
# - For Linux: gcc-multilib, gcc-aarch64-linux-gnu
# - For macOS: osxcross
# - For Windows: Visual Studio Build Tools

[build]
target = "x86_64-pc-windows-msvc"  # Default target for the current platform
