// apps/dler/src/cmds/build/cmd.ts

import type { BuildOptions } from "@reliverse/build";
import { applyPresets, runBuildOnAllPackages, validateAndExit } from "@reliverse/build";
import type { GoBuildOptions } from "@reliverse/config/impl/build";
import { clearLoggerInternalsInPackages, replaceExportsInPackages } from "@reliverse/helpers";
import { logger } from "@reliverse/relinka";
import { defineCommand, option } from "@reliverse/rempts";
import { z } from "zod";

export default defineCommand({
  name: "build",
  description:
    "Build all workspace packages using configurable bundler (mkdist for libraries, bun for apps) with dler.ts configuration. Auto-detects frontend apps and libraries. Supports presets: --production, --dev, --library, --react, --node, --monorepo.",
    examples: [
      "dler build",
      'dler build --filter "rempts,@reliverse/build"',
      'dler build --filter "@reliverse/dler-*"',
      'dler build --ignore "@reliverse/*"',
      'dler build --ignore "@reliverse/relico" --ignore "@reliverse/dler-v1"',
      'dler build --ignore "@reliverse/relico @reliverse/dler-v1"',
      "dler build --cwd /path/to/monorepo",
      "dler build --cwd /path/to/monorepo --ignore @reliverse/*",
      "dler build --concurrency 8",
      "dler build --concurrency 2 --stopOnError",
      "dler build --ignore @reliverse/* --concurrency 6 --stopOnError",
      "dler build --verbose",
      "dler build --verbose --ignore @reliverse/*",
      "dler build --verbose --concurrency 2 --stopOnError",
      "dler build --watch",
      "dler build --watch --verbose",
      "dler build --target node --format cjs",
      "dler build --minify --sourcemap linked",
      "dler build --target browser --format esm --splitting false",
      "dler build --external react --external react-dom",
      "dler build --watch --target browser --minify --sourcemap inline",
      "dler build --production",
      "dler build --dev",
      "dler build --bytecode --format cjs --target bun",
      "dler build --minifyWhitespace --minifySyntax --minifyIdentifiers",
      "dler build --drop console.log --drop debugger",
      'dler build --env PUBLIC_* --define \'{"__VERSION__":"1.0.0"}\'',
      "dler build --banner 'use client' --footer '// built with dler'",
      "dler build --entryNaming '[dir]/[name].[ext]' --chunkNaming '[name]-[hash].[ext]'",
      "dler build --compile --production",
      "dler build --noCache --verbose",
      "dler build --packages external --external 'react*'",
      "dler build --publicPath /assets/ --root ./src",
      "",
      "# Standalone Executable Examples:",
      "dler build --compile --production --target bun",
      "dler build --compile --target node --format cjs --minify",
      "dler build --compile --bytecode --format cjs --target bun",
      "dler build --compile --windowsIcon app.ico --windowsTitle 'My App'",
      "dler build --compile --production --env inline --drop console.log",
      "",
      "# Note: --compile generates executables alongside bundles",
      "# For Bun executables, use --target bun --format cjs --bytecode for best performance",
      "# For Node executables, use --target node --format cjs",
      "",
      "# Preset Examples:",
      "dler build --production  # Optimized for production",
      "dler build --dev         # Development mode with watch",
      "dler build --library     # Library build (external deps)",
      "dler build --react       # React app with JSX support",
      "dler build --node        # Node.js server build",
      "dler build --monorepo    # Monorepo optimized build",
      "",
      "# Bundler Examples:",
      "dler build --bundler mkdist  # Use mkdist bundler (default for libraries)",
      "dler build --bundler bun     # Use Bun bundler (default for apps)",
      "dler build --bundler mkdist --kind library",
      "dler build --bundler bun --kind library",
      "",
      "# Note: mkdist preserves file structure and is ideal for libraries",
      "# bun bundles dependencies and is ideal for applications",
      "",
      "# New Bun bundler features:",
      "dler build --noBundle --target node",
      "dler build --reactFastRefresh --watch",
      "dler build --noClearScreen --watch",
      "dler build --windowsHideConsole --windowsIcon app.ico --compile",
      "dler build --app --serverComponents",
      "dler build --debugDumpServerFiles --debugNoMinify",
      "",
      "# Enhanced Features:",
      "dler build --bundleAnalyzer --performanceMonitoring",
      "dler build --generateTypes --typeCheck",
      "dler build --macros --sideEffects false",
      "dler build --bundleSizeLimit 1048576 --performanceBudget '{\"maxBundleSize\":1048576}'",
      "dler build --imageOptimization --fontOptimization --cssOptimization",
      "dler build --svgAsReact --cssModules --workerSupport",
      "dler build --plugins 'react-refresh,typescript-declarations,bundle-analyzer'",
      "",
      "# Frontend App Examples:",
      "dler build --devServer --watch --open --reactFastRefresh",
      "dler build --production --html --cssChunking --bundleAnalyzer",
      "dler build --target browser --format esm --html --cssChunking --svgAsReact",
      "dler build --devServer --port 8080 --open --cssModules",
      "dler build --html --publicAssets static --cssChunking --imageOptimization",
      "",
      "# Full-stack App Examples:",
      "dler build --target browser --format esm --html --assets public --workerSupport",
      "dler build --devServer --watch --target browser --html --performanceMonitoring",
      "",
      "# Library Examples:",
      "dler build --library --generateTypes --typeCheck",
      "dler build --target bun --format esm --generateTypes --bundleAnalyzer",
      "dler build --target node --format cjs --generateTypes --sideEffects false",
      "",
      "# Configuration Examples:",
      "# Create dler.ts in your monorepo root:",
      "# export default {",
      "#   build: {",
      "#     global: { target: 'bun', format: 'esm' },",
      "#     packages: { 'my-package': { minify: true, generateTypes: true } },",
      "#     patterns: [{ pattern: 'apps/*', config: { target: 'browser', html: true, bundleAnalyzer: true } }]",
      "#   }",
      "# }",
      "",
      "# Note: Configuration is only supported via dler.ts",
      "# package.json build fields are not supported",
      "",
      "# Config Discovery Examples:",
      "dler build --maxConfigDepth 5",
      "",
      "# TSConfig Validation Examples:",
      "dler build --validateTsconfig",
      "dler build --strictTsconfig",
      "dler build --validateTsconfig --verbose",
      "dler build --noValidateTsconfig",
      "",
      "# Note: --validateTsconfig checks tsconfig.json for common issues",
      "# Use --strictTsconfig to make validation errors fatal",
      "",
      "# DTS Provider Examples:",
      "dler build --dtsProvider dts-bundle-generator",
      "dler build --dtsProvider api-extractor",
      "dler build --dtsProvider typescript",
      "dler build --dtsProvider mkdist",
      "dler build --generateTypes --dtsProvider dts-bundle-generator",
      "",
      "# Note: dts-bundle-generator is the default provider for better bundling",
      "# mkdist provider offers VFS-based processing with automatic relative import resolution",
      "# Use --dtsProvider to override the default provider",
      "",
      "# Go Build Examples:",
      "dler build --go-provider xgo",
      "dler build --go-provider native",
      "dler build --go-targets linux/amd64",
      "dler build --go-targets 'linux/amd64,windows/amd64,darwin/arm64'",
      "dler build --go-output-dir release",
      "dler build --go-output-name my-binary",
      "dler build --go-build-mode c-shared",
      "dler build --go-ldflags '-s -w -X main.version=1.0.0'",
      "dler build --go-main-file main.go",
      "dler build --go-version 1.21.0",
      "dler build --go-enable",
      "",
      "# Note: Go build is auto-detected if .go files exist in the package",
      "# Use --go-enable to explicitly enable, or configure in dler.ts",
      "# Use --go-provider xgo for cross-compilation (requires xgo installed)",
      "# Use --go-provider native for native builds (limited cross-compilation)",
      "",
      "# Build Type Selection Examples:",
      "dler build --go-only",
      "dler build --ts-only",
      "dler build --go-only --go-targets linux/amd64",
      "dler build --ts-only --target node --format cjs",
      "",
  options: {
    verbose: option(
      z.boolean().default(false),
      {
        description: "Verbose mode (default: false)",
      },
    ),
  },
  handler: async ({ flags }) => {
    console.log("Build command temporarily disabled - needs full migration");
  },
});
