// autogenerated by `dler config`
// don't edit this file manually

export interface ConfigModEntry {
  version: string;
  mode: string;
  main: string;
  input: string;
  output: string;
}

export interface DotConfig {
  dler?: ConfigModEntry;
}

export const dotConfig: DotConfig = {
  dler: {
    version: "1.7.73",
    mode: "copy-internal",
    main: "defineConfig",
    input: "src/libs/cfg/cfg-mod.ts",
    output: ".config/types/dler.schema.ts",
  },
};
